spring:
    application:
        name: pumplog
    datasource:
        url: jdbc:postgresql://localhost:5432/PumpLog
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    # Hibernate configuration
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update